# Generated by Django 5.0 on 2023-12-08 00:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Clientes", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tipo_cliente",
            options={
                "verbose_name": "Tipo_Cliente",
                "verbose_name_plural": "Tipos_Clientes",
            },
        ),
        migrations.AlterModelTable(
            name="tipo_cliente",
            table="tipo_cliente",
        ),
    ]
