# Generated by Django 5.0 on 2023-12-09 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("Clientes", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MarcaTarjeta",
            fields=[
                ("brand_id", models.AutoField(primary_key=True, serialize=False)),
                ("brand_name", models.CharField(max_length=30)),
            ],
            options={
                "verbose_name": "Marca de Tarjeta",
                "verbose_name_plural": "Marcas de Tarjeta",
                "db_table": "marca_tarjeta",
                "ordering": ["-brand_id"],
            },
        ),
        migrations.CreateModel(
            name="Tarjeta",
            fields=[
                ("card_id", models.AutoField(primary_key=True, serialize=False)),
                ("number", models.CharField(max_length=16)),
                ("cvv", models.IntegerField()),
                ("issue_date", models.CharField(max_length=8)),
                ("expiration_date", models.CharField(max_length=8)),
                ("type", models.TextField()),
                (
                    "brand",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Tarjetas.marcatarjeta",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Clientes.cliente",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tarjeta",
                "verbose_name_plural": "Tarjetas",
                "db_table": "tarjeta",
                "ordering": ["-client"],
            },
        ),
    ]
