# Generated by Django 5.0 on 2023-12-06 23:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("Clientes", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TipoCuenta",
            fields=[
                ("type_name", models.CharField(max_length=30)),
                ("type_id", models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                "verbose_name": "Tipo de cuenta",
                "verbose_name_plural": "Tipo de cuentas",
                "db_table": "tipo_cuenta",
                "ordering": ["-type_id"],
            },
        ),
        migrations.CreateModel(
            name="Cuenta",
            fields=[
                ("account_id", models.AutoField(primary_key=True, serialize=False)),
                ("balance", models.IntegerField()),
                ("iban", models.CharField(max_length=100)),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Clientes.cliente",
                    ),
                ),
                (
                    "type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Cuentas.tipocuenta",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cuenta",
                "verbose_name_plural": "Cuentas",
                "db_table": "cuenta",
                "ordering": ["-account_id"],
            },
        ),
    ]
