# Generated by Django 5.0 on 2023-12-09 11:32

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Sucursal",
            fields=[
                ("branch_id", models.AutoField(primary_key=True, serialize=False)),
                ("branch_name", models.CharField(max_length=50)),
                ("branch_number", models.IntegerField()),
            ],
            options={
                "verbose_name": "Sucursal",
                "verbose_name_plural": "Sucursales",
                "db_table": "sucursal",
                "ordering": ["-branch_id"],
            },
        ),
    ]
