# Generated by Django 5.0 on 2023-12-09 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("Clientes", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Prestamo",
            fields=[
                ("loan_id", models.AutoField(primary_key=True, serialize=False)),
                ("loan_type", models.CharField(max_length=30)),
                ("loan_date", models.DateField()),
                ("loan_ammount", models.IntegerField()),
                ("loan_preapproval", models.CharField(max_length=30)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Clientes.cliente",
                    ),
                ),
            ],
            options={
                "verbose_name": "Prestamo",
                "verbose_name_plural": "Prestamos",
                "db_table": "prestamo",
                "ordering": ["-loan_id"],
            },
        ),
    ]
